#
# docker-compose.yml
# Robert Howe <rc@rchowe.com>
#
# This is the **production** docker-compose file, which does not include a
# bundled database and will force the app to use the production settings.
#

version: '3'

services:
    cormackapp:
      restart: always
      build: .
      volumes:
        - .:/opt/services/cormack/src
        - static_volume:/opt/services/cormack/src/static-collect
        - /var/local/cormack/app:/opt/services/cormack/src/media
      environment:
        - DJANGO_SETTINGS_MODULE=config.settings.production
        - CORMACK_DEV_MODE={CORMACK_DEV_MODE}
      networks:
        - nginx_network
      ports:
        - 8081:8002
      extra_hosts:
        - "db:45.32.190.142"

    nginx:
      restart: always
      image: nginx:1.13
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./config/nginx/conf.d:/etc/nginx/conf.d
        - static_volume:/opt/services/cormack/src/static-collect
        - /var/local/cormack/app:/opt/services/cormack/src/media
        - ./config/ssl:/etc/letsencrypt
        - certbot_volume:/var/www/certbot
      depends_on:
        - cormackapp
      networks:
        - nginx_network
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
    certbot:
      image: certbot/certbot
      volumes: 
        - ./config/ssl:/etc/letsencrypt
        - certbot_volume:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  ssl_certificate_volume:
  certbot_volume:
