#
# docker-compose.development.yml
# Robert Howe <rc@rchowe.com>
#
# This docker-compose file was the original that came with this software
# package, which includes a development database. Given that we don't want to
# run a database in a Docker container in a production environment, please use
# this file specifically for development and the regular docker-compose.yml for
# production.
#

version: '3'

services:
    cormackapp:
      restart: always
      build: .
      volumes:
        - .:/opt/services/cormack/src
        - static_volume:/opt/services/cormack/src/static-collect
        - media_volume:/opt/services/cormack/src/media
        - ssl_certificate_volume:/opt/services/cormack/src/config/ssl
      environment:
        - DJANGO_SETTINGS_MODULE=config.settings.production
      networks:
        - nginx_network
        - db_network
      depends_on:
        - db
      ports:
        - 8081:8002

    nginx:
      restart: always
      image: nginx:1.13
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./config/nginx/conf.d:/etc/nginx/conf.d
        - static_volume:/opt/services/cormack/src/static-collect
        - media_volume:/opt/services/cormack/src/media
        - ssl_certificate_volume:/opt/services/cormack/src/config/ssl
      depends_on:
        - cormackapp
      networks:
        - nginx_network

    db:
      restart: always
      image: postgres:10
      volumes:
         - db_volume:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=cormack_jms
      networks:
        - db_network
      ports:
        - 5432:5432

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
  static_volume:
  media_volume:
  ssl_certificate_volume: