# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-02-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocom_xero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeroinvoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Invoice No.'),
        ),
        migrations.AlterField(
            model_name='xeroinvoice',
            name='other_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Other ID'),
        ),
        migrations.AlterField(
            model_name='xeroinvoice',
            name='other_name',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Other Name'),
        ),
    ]
