# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-02-19 21:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocom_xero', '0002_auto_20180220_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_id', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Xero ID')),
                ('xero_type', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Xero Type')),
                ('xero_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Xero Data')),
                ('xero_text', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Description')),
                ('xero_code', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Xero Entity',
                'db_table': 'xero_entity',
                'verbose_name_plural': 'Xero Entities',
            },
        ),
    ]
