# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-02-22 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocom_xero', '0003_xeroentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('rsa_key', models.CharField(max_length=1000, verbose_name='RSA Key')),
                ('consumer_key', models.CharField(max_length=1000, verbose_name='Consumer Key')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'xero_connection',
                'verbose_name': 'Xero Connection',
                'verbose_name_plural': 'Xero Connections',
            },
        ),
    ]
