# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-03-05 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocom_xero', '0005_xeropurchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroinvoice',
            name='xero_id',
            field=models.CharField(db_index=True, default='NONE', max_length=255, verbose_name='Xero ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xeropurchaseorder',
            name='xero_id',
            field=models.CharField(db_index=True, default='NONE', max_length=255, verbose_name='Xero ID'),
            preserve_default=False,
        ),
    ]
