# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2017-12-07 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171207_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subbie',
            options={'verbose_name': 'Subbie', 'verbose_name_plural': 'Subbies'},
        ),
        migrations.AlterModelTable(
            name='subbie',
            table='subbie',
        ),
    ]
