# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2017-12-13 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171212_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hash',
            options={'verbose_name': 'Hash', 'verbose_name_plural': 'Hashes'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobcost',
            options={'verbose_name': 'Job Cost', 'verbose_name_plural': 'Job Costs'},
        ),
        migrations.AlterModelOptions(
            name='jobtask',
            options={'verbose_name': 'Job Task', 'verbose_name_plural': 'Job Tasks'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'verbose_name': 'Repair', 'verbose_name_plural': 'Repairs'},
        ),
        migrations.AlterModelOptions(
            name='repaircost',
            options={'verbose_name': 'Repair Cost', 'verbose_name_plural': 'Repair Costs'},
        ),
        migrations.AlterModelTable(
            name='hash',
            table='hash',
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
        migrations.AlterModelTable(
            name='jobcost',
            table='job_cosst',
        ),
        migrations.AlterModelTable(
            name='jobtask',
            table='job_task',
        ),
        migrations.AlterModelTable(
            name='repair',
            table='repair',
        ),
        migrations.AlterModelTable(
            name='repaircost',
            table='repair_cost',
        ),
    ]
