# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-01-05 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_codefiletype_can_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completed Date'),
        ),
        migrations.AddField(
            model_name='repair',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repair',
            name='files',
            field=models.ManyToManyField(to='api.FileUpload'),
        ),
        migrations.AddField(
            model_name='repair',
            name='notes',
            field=models.ManyToManyField(to='api.Note'),
        ),
    ]
