# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-01-05 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180105_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='costs',
            field=models.ManyToManyField(to='api.JobCost'),
        ),
        migrations.AddField(
            model_name='repair',
            name='costs',
            field=models.ManyToManyField(to='api.RepairCost'),
        ),
    ]
