# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-01-09 01:02
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_auto_20180108_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='prefix',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=api.models.upload_path_by_prefix),
        ),
    ]
