# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-01-09 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180109_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='costs',
            new_name='job_costs',
        ),
        migrations.RenameField(
            model_name='repair',
            old_name='costs',
            new_name='repair_costs',
        ),
    ]
