# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-01-30 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_jobtask_slot_order'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='job',
        #     name='job_tasks',
        # ),
        migrations.AddField(
            model_name='jobtask',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Job', verbose_name='Job'),
            preserve_default=False,
        ),
    ]
