# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-02-01 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180131_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetasktype',
            name='job_date_field',
            field=models.CharField(default='', max_length=128, verbose_name='Job Date Field'),
        ),
    ]
