# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-02-05 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_codetasktype_job_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Job Number'),
        ),
    ]
