# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-02-21 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180222_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='xero_item_code',
            field=models.CharField(default='NONE', max_length=100, verbose_name='Xero Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaircost',
            name='xero_item_code',
            field=models.CharField(default='NONE', max_length=100, verbose_name='Xero Item'),
            preserve_default=False,
        )
    ]
