# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-02-22 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20180222_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='subcontractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='details',
            field=models.CharField(max_length=100, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='repaircost',
            name='details',
            field=models.CharField(max_length=100, verbose_name='Details'),
        ),
    ]
