# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-02-26 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180226_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtask',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accept Date'),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reject Date'),
        ),
    ]
