# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-02-28 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20180228_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefiletype',
            name='admin_only',
            field=models.BooleanField(default=False, verbose_name='Admin Only'),
        ),
        migrations.AlterField(
            model_name='codetasktype',
            name='job_date_field',
            field=models.CharField(default='', max_length=128, verbose_name='Job Date Field'),
        ),
    ]
