# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-03-05 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocom_xero', '0008_xeroentity_total'),
        ('api', '0042_auto_20180228_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='xero_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocom_xero.XeroEntity', verbose_name='Xero Purchase Order'),
        ),
    ]
