# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-03-07 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180307_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active_start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active Start Date')),
                ('active_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Active End Date')),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Mix',
                'verbose_name_plural': 'Mixes',
                'db_table': 'code_mix',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CodeMix', verbose_name='Mix'),
        ),
    ]
