# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-03-08 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20180308_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDrains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active_start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active Start Date')),
                ('active_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Active End Date')),
                ('metres', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Metres')),
                ('drain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CodeDrainType', verbose_name='Drain Type')),
            ],
            options={
                'verbose_name_plural': 'Job Drains',
                'verbose_name': 'Job Drains',
                'db_table': 'job_drains',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_drains',
            field=models.ManyToManyField(to='api.JobDrains'),
        ),
    ]
