# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-03-09 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180308_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='has_conduit',
            field=models.BooleanField(default=False, verbose_name='Has Conduit'),
        ),
    ]
