# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-04-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_copy_end_date_to_active_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase Order Number'),
        ),
    ]
