# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-04-13 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_job_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbie',
            name='display_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Display Order'),
        ),
    ]
