# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-07-17 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_role_client_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTimeOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active_start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active Start Date')),
                ('active_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Active End Date')),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Time Of Day',
                'verbose_name_plural': 'Times Of Day',
                'db_table': 'code_time_of_day',
            },
        ),
        migrations.AlterField(
            model_name='role',
            name='client_manager',
            field=models.BooleanField(default=False, verbose_name='Client Manager'),
        ),
    ]
