# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-07-16 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_role_client_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cut_and_sealed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cut And Sealed Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='dug_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dug Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='poured_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Poured Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='prepared_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prepared Date'),
        )
    ]
