# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-07-17 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20180717_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='base_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Base Inspection Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='part_a_date',
            field=models.DateField(blank=True, null=True, verbose_name='Part A Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='piers_date',
            field=models.DateField(blank=True, null=True, verbose_name='Proposed Piers Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='piers_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Piers Inspection Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='piers_concrete_date',
            field=models.DateField(blank=True, null=True, verbose_name='Piers Inspection Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pour_date',
            field=models.DateField(blank=True, null=True, verbose_name='Proposed Pour Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rock_booked_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rock Booked Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='steel_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Steel Inspection Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='waste_date',
            field=models.DateField(blank=True, null=True, verbose_name='Waste Date'),
        ),
    ]
