# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-07-18 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20180717_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='codejobtype',
            name='background_colour',
            field=models.CharField(default='#ffffff', max_length=128),
        ),
        migrations.AddField(
            model_name='codejobtype',
            name='foreground_colour',
            field=models.CharField(default='#8080ff', max_length=128),
        ),
    ]
