# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-07-24 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20180724_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pod_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_pod_supplier', to='api.CodeSupplier', verbose_name='POD Supplier'),
        ),
        migrations.AddField(
            model_name='job',
            name='rock_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_rock_supplier', to='api.CodeSupplier', verbose_name='Rock Supplier'),
        ),
        migrations.AddField(
            model_name='job',
            name='steel_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_steel_supplier', to='api.CodeSupplier', verbose_name='Steel Supplier'),
        ),
    ]
