# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-07-30 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_role_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='down_pipes_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Down Pipes Comment'),
        ),
        migrations.AddField(
            model_name='job',
            name='down_pipes_installed',
            field=models.NullBooleanField(verbose_name='Down Pipes Installed'),
        ),
        migrations.AddField(
            model_name='job',
            name='gas_line_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gas Line Comment'),
        ),
        migrations.AddField(
            model_name='job',
            name='gas_line_installed',
            field=models.NullBooleanField(default=False, verbose_name='Gas Line Installed'),
        ),
        migrations.AddField(
            model_name='job',
            name='good_access_rear_paving',
            field=models.NullBooleanField(verbose_name='Good Access for Rear Paving'),
        ),
        migrations.AddField(
            model_name='job',
            name='pacing_heights_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paving Heights Comment'),
        ),
        migrations.AddField(
            model_name='job',
            name='pacing_within_tolerance',
            field=models.NullBooleanField(verbose_name='Paving Heights Within Tolerance'),
        ),
        migrations.AddField(
            model_name='job',
            name='rear_paving_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rear Paving Comment'),
        ),
        migrations.AddField(
            model_name='job',
            name='rebates_brickwork',
            field=models.NullBooleanField(verbose_name='Rebates Flush With Brickwork'),
        ),
        migrations.AddField(
            model_name='job',
            name='rebates_brickwork_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gas Line Comment'),
        ),
        migrations.AddField(
            model_name='job',
            name='risers_correct_location',
            field=models.NullBooleanField(verbose_name='Risers in Correct Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='risers_location_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Risers Location Comment'),
        ),
    ]
