# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-07-24 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20180724_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='building_inspector',
        ),
        migrations.AddField(
            model_name='job',
            name='building_inspector_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_building_inspector_supplier', to='api.CodeSupplier', verbose_name='Inspector Supplier'),
        ),
        migrations.AlterField(
            model_name='job',
            name='termite_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_termite_supplier', to='api.CodeSupplier', verbose_name='Termite Inspector Supplier'),
        ),
    ]
