# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-10-29 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20180802_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmanager',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='clientmanager',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodeFileType'),
        ),
        migrations.AlterField(
            model_name='job',
            name='base_inspection_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_inspection_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='building_inspector_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_building_inspector_supplier', to='api.CodeSupplier', verbose_name='Inspector Supplier'),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='job',
            name='drain_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodeDrainType', verbose_name='Drain Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CodeJobType', verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodeMix', verbose_name='Mix'),
        ),
        migrations.AlterField(
            model_name='job',
            name='part_a_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_a_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='paving_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodePavingColour', verbose_name='Paving Colour'),
        ),
        migrations.AlterField(
            model_name='job',
            name='paving_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodePavingType', verbose_name='Paving Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='piers_inspection_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piers_inspection_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='piers_concrete_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piers_concrete_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='piers_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piers_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pod_delivery_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pod_delivery_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pod_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_pod_supplier', to='api.CodeSupplier', verbose_name='POD Supplier'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pour_date_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pour_date_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rock_booked_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rock_booked_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rock_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_rock_supplier', to='api.CodeSupplier', verbose_name='Rock Supplier'),
        ),
        migrations.AlterField(
            model_name='job',
            name='steel_delivery_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='steel_delivery_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='steel_inspection_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='steel_inspection_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='steel_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_steel_supplier', to='api.CodeSupplier', verbose_name='Steel Supplier'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sub_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Subbie', verbose_name='SubContractor'),
        ),
        migrations.AlterField(
            model_name='job',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Supervisor', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='job',
            name='termite_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_termite_supplier', to='api.CodeSupplier', verbose_name='Termite Inspector Supplier'),
        ),
        migrations.AlterField(
            model_name='job',
            name='waste_time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_time_of_day', to='api.CodeTimeOfDay', verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='xero_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ocom_xero.XeroEntity', verbose_name='Xero Purchase Order'),
        ),
        migrations.AlterField(
            model_name='jobdrains',
            name='drain_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CodeDrainType', verbose_name='Drain Type'),
        ),
        migrations.AlterField(
            model_name='jobpurchaseorder',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodePurchaseOrderType', verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Job'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repair_subbie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Subbie', verbose_name='Repair Subbie'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repair_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CodeRepairType', verbose_name='Repair Type'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='xero_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ocom_xero.XeroEntity', verbose_name='Xero Purchase Order'),
        ),
        migrations.AlterField(
            model_name='subbie',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodeSubbieType'),
        ),
        migrations.AlterField(
            model_name='subbie',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Job', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='task',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Subbie', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CodeTaskType', verbose_name='Task Type'),
        ),
    ]
