# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-11-27 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20181029_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contractor_swms',
            field=models.NullBooleanField(verbose_name='Contractor SWMS'),
        ),
    ]
