# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-11-27 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_job_contractor_swms'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved Date'),
        ),
    ]
