# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

# Generated by Django 1.10.7 on 2018-11-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_job_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Update the Code so it has a value
        migrations.RunSQL(
            sql="update job set code = concat(job.id, '-', upper(left(code_job_type.description, 1))) from code_job_type where code_job_type.id = job.job_type_id"
        )
    ]
