# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-04 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='gas_line_installed',
            field=models.NullBooleanField(default=None, verbose_name='Gas Line Installed'),
        ),
    ]
