# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-27 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_repair_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='suburb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suburb'),
        ),
    ]
