# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 03:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_repair_no_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='set_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='Set Out Date'),
        ),
    ]
