# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 04:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20190521_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefiletype',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Is Internal'),
        ),
        migrations.AddField(
            model_name='codetasktype',
            name='job_date_order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jobs Date Order'),
        ),
    ]
