# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_auto_20190521_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='drain_date',
            field=models.DateField(blank=True, null=True, verbose_name='Drain Date'),
        ),
    ]
