# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_job_wanted_pour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='piers',
            field=models.IntegerField(default=0, verbose_name='Piers'),
        ),
    ]
