# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_job_piers'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pier_inspection_done',
            field=models.BooleanField(default=False, verbose_name='Pier Inspection Done'),
        ),
    ]
