# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_job_pier_inspection_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='base_inspection_done',
            field=models.BooleanField(default=False, verbose_name='Base Inspection Done'),
        ),
        migrations.AddField(
            model_name='job',
            name='steel_inspection_done',
            field=models.BooleanField(default=False, verbose_name='Steel Inspection Done'),
        ),
    ]
