# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20190521_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='concrete_date',
            field=models.DateField(blank=True, null=True, verbose_name='Concrete Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='concrete_mix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concrete Mix'),
        ),
    ]
