# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20190521_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slab_schedule_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
