# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_job_slab_schedule_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='base_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_base_inspector_supplier', to='api.CodeSupplier', verbose_name='Base Inspector'),
        ),
        migrations.AddField(
            model_name='job',
            name='pump_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_pump_inspector_supplier', to='api.CodeSupplier', verbose_name='Pump Supplier'),
        ),
    ]
