# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-03 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20190521_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='base_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_base_inspector_supplier', to='api.Subbie', verbose_name='Base Inspector'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pump_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_pump_inspector_supplier', to='api.Subbie', verbose_name='Pump Supplier'),
        ),
    ]
