# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-01 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20190603_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='base_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Base Date'),
        ),
    ]
