# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-09 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_job_concrete_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='concrete_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='piers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Piers'),
        ),
    ]
