# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-15 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20191015_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='call_up_date_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
