# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-15 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_job_call_up_date_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pier_concrete',
            field=models.DateField(blank=True, null=True, verbose_name='Pier Concrete'),
        ),
        migrations.AddField(
            model_name='job',
            name='pier_concrete_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
