# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20191015_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='repair',
            name='end_date_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
