# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-23 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_repair_repair_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='base_date',
            field=models.DateField(blank=True, null=True, verbose_name='Base Date'),
        ),
    ]
