# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-23 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Depot', verbose_name='Depot'),
        ),
    ]
