# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-23 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_job_depot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depot',
            options={'verbose_name': 'Depot', 'verbose_name_plural': 'Depots'},
        ),
        migrations.RemoveField(
            model_name='depot',
            name='name',
        ),
        migrations.AddField(
            model_name='depot',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Depot'),
        ),
    ]
