# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-23 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_auto_20191023_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Depot Description'),
        ),
    ]
