# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_depot_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='color',
        ),
        migrations.RemoveField(
            model_name='job',
            name='depot',
        ),
        migrations.AddField(
            model_name='depot',
            name='colour',
            field=models.CharField(blank=True, default='#8080ff', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Depot', verbose_name='Depot'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='depot',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
