# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-23 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20191023_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depot',
            old_name='colour',
            new_name='background_colour',
        ),
    ]
