# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-24 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_job_depot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDepotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active_start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active Start Date')),
                ('active_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Active End Date')),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('background_colour', models.CharField(blank=True, default='#ffffff', max_length=128, null=True)),
                ('foreground_colour', models.CharField(blank=True, default='#8080ff', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Depot Type',
                'verbose_name_plural': 'Depot Types',
                'db_table': 'code_depot_type',
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='task',
            name='depot',
        ),
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Job', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='task',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Subbie', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodeTaskType', verbose_name='Task Type'),
        ),
        migrations.DeleteModel(
            name='Depot',
        ),
        migrations.AddField(
            model_name='job',
            name='depot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodeDepotType', verbose_name='Depot Type'),
        ),
        migrations.AddField(
            model_name='task',
            name='depot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CodeDepotType', verbose_name='Depot Type'),
        ),
    ]
