# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-29 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20191024_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='base_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Base Date'),
        ),
    ]
