# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20191218_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroOAuth2Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(max_length=1024)),
            ],
        ),
    ]
