# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-18 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_xerooauth2information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerooauth2information',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='xerooauth2information',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
