# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

#
#
#

# Generated by Django 1.11.13 on 2018-06-15 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstatemodelfield',
            name='can_read',
        ),
        migrations.RemoveField(
            model_name='groupstatemodelfield',
            name='can_update',
        ),
        migrations.AddField(
            model_name='groupstatemodelfield',
            name='deny_read',
            field=models.BooleanField(default=True, verbose_name='Deny Read'),
        ),
        migrations.AddField(
            model_name='groupstatemodelfield',
            name='deny_update',
            field=models.BooleanField(default=True, verbose_name='Deny Update'),
        ),
    ]
