# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

#
#
#

# Generated by Django 1.9.6 on 2018-08-02 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocom', '0003_auto_20180615_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppermissions',
            options={'ordering': ['group__name'], 'verbose_name': 'Group Permission', 'verbose_name_plural': 'Group Permission'},
        ),
        migrations.AlterModelOptions(
            name='groupstate',
            options={'ordering': ['state_name'], 'verbose_name': 'Group State', 'verbose_name_plural': 'Group State'},
        ),
        migrations.AlterModelOptions(
            name='groupstatemodel',
            options={'ordering': ['model_name'], 'verbose_name': 'Group State Model', 'verbose_name_plural': 'Group State Models'},
        ),
        migrations.AlterModelOptions(
            name='groupstatemodelfield',
            options={'ordering': ['field_name'], 'verbose_name': 'Group State Model Field', 'verbose_name_plural': 'Group State Model Fields'},
        ),
    ]
