# -*- coding: utf-8 -*-

#
#  Copyright (C) 2019 Ocom Software- All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Ocom Software <licence@ocom.com.au, 2019
#
#

#
#
#

# Generated by Django 1.9.6 on 2018-08-03 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocom', '0004_auto_20180802_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermissions',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='groupstate',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Details'),
        ),
    ]
